version: 2

jobs:
  test:
    machine:
      docker_layer_caching: true
    working_directory: ~/cypress-image-diff
    steps:
      - checkout
      - run:
          name: Build docker
          command: make build
      - run:
          name: Run eslint
          command: make lint-test
      - run:
          name: Run unit
          command: make unit-test
      - run:
          name: Run e2e test
          command: make e2e-test

  build_and_publish:
    machine:
      docker_layer_caching: true
    working_directory: ~/cypress-image-diff
    steps:
      - checkout
      - run:
          name: Build docker
          command: make build
      - run:
          name: Publish (semantic release - main only)
          command: make publish

workflows:
  version: 2
  cypressimagediff:
    jobs:
      - test
      - build_and_publish:
          requires:
            - test
          filters:
            branches:
              only:
                - main
