version: 2
aliases:
  - &node_version node:12.14.1

jobs:
  test:
    machine:
      docker_layer_caching: true
    working_directory: ~/cypress-image-diff
    steps:
      - checkout
      - run: npm ci
      - run:
          name: Build docker
          command: make build
      - run:
          name: Run eslint
          command: make lint-test
      - run:
          name: Run unit
          command: make unit-test
      - run:
          name: Run eslint
          command: make e2e-test

  build_and_publish:
    docker:
      - image: *node_version
    working_directory: ~/cypress-image-diff
    steps:
      - checkout
      - run: npm ci
      - run:
          name: Build
          command: npm run build
      - run:
          name: Publish (semantic release - main only)
          command: ./node_modules/.bin/semantic-release

workflows:
  version: 2
  cypressimagediff:
    jobs:
      - lint
      - unit
      - e2e
      - build_and_publish:
          requires:
            - lint
            - unit
            - e2e
          filters:
            branches:
              only:
                - main
